[package]
name = "rust_cli_sample"
version = "0.0.1"
edition = "2021"

[dependencies]
clap = { version = "4.4.12", features = ["derive"] }
library = { path = "./library" }

[workspace]
members = ["library"]